services:
  acme.sh:
    image: "neilpang/acme.sh"
    container_name: acme.sh
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - certdata:/acme.sh
    command: daemon

volumes:
  certdata:
    name: tls_certificates
